"""Add image_url to Category

Revision ID: 0e3dbad68657
Revises: 4eccf333baf1
Create Date: 2025-09-05 23:46:47.922572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3dbad68657'
down_revision = '4eccf333baf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
