"""edit share model

Revision ID: 2c1d99ed5061
Revises: 923ccc164c28
Create Date: 2025-08-23 12:00:03.794564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1d99ed5061'
down_revision = '923ccc164c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('object_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('share_token_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('share_shared_with_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['target_user_id'], ['id'])
        batch_op.drop_column('token')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('shared_with')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('share_shared_with_fkey'), 'user', ['shared_with'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('share_token_key'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')
        batch_op.drop_column('target_user_id')

    # ### end Alembic commands ###
