"""Ajout de la table Document avec supabase_url

Revision ID: 474a3494fa9c
Revises: 
Create Date: 2025-07-20 17:15:25.899491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474a3494fa9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_url', sa.String(length=500), nullable=False))
        batch_op.drop_column('r2_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r2_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('supabase_url')

    # ### end Alembic commands ###
